[project]
name = "codi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fire>=0.7.1",
    "huggingface-hub>=0.30.0,<1.0",
    "matplotlib>=3.10.7",
    "pandas>=2.3.3",
]
